elasticsearch:  
  image: elasticsearch:2.0.0
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
logstash:  
  image: logstash:2.0.0-1
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
  - ./logstash:/etc/logstash/conf.d
  ports:
  - "5000:5000"
  links:
    - elasticsearch
    - zookeeper
kibana:  
  image: kibana:4.2.0
  ports:
    - "5601:5601"
  links:
    - elasticsearch

kafka:
  image: wurstmeister/kafka
  links:
    - zookeeper
  ports:
    - "9092:9092"
  environment:
    KAFKA_LOG_DIRS: /kafka
    KAFKA_BROKER_ID: 1
    KAFKA_CREATE_TOPICS: loggin:1:1
    KAFKA_ADVERTISED_HOST_NAME: 10.161.7.91
    KAFKA_ADVERTISED_PORT: 9092
    KAFKA_LOG_RETENTION_HOURS: "168"
    KAFKA_LOG_RETENTION_BYTES: "100000000"
    KAFKA_ZOOKEEPER_CONNECT:  zookeeper:2181

zookeeper:
  image: elevy/zookeeper:latest
  environment:
    MYID: 1
    SERVERS: zookeeper
  ports:
    - "2181:2181"

kafka-manager:
  image: sheepkiller/kafka-manager:latest
  ports:
    - "9000:9000"
  links:
    - zookeeper
    - kafka
  environment:
    ZK_HOSTS: zookeeper:2181
    APPLICATION_SECRET: letmein
    KM_ARGS: -Djava.net.preferIPv4Stack=true
