elasticsearch:  
  image: elasticsearch:2.0.0
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
logstash:  
  image: logstash:2.0.0-1
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
  - ./logstash:/etc/logstash/conf.d
  ports:
  - "5000:5000"
  links:
    - elasticsearch
kibana:  
  image: kibana:4.2.0
  ports:
    - "5601:5601"
  links:
    - elasticsearch
#activemq:
#    image: rmohr/activemq:5.11.1
#   ports:
#      - "61616:61616"
#      - "8161:8161"
zookeeper:
    image: wurstmeister/zookeeper
kafka:
   image: wurstmeister/kafka
   links:
      - zookeeper
   command: "/bin/bash /broker_helpers/configure_and_start_broker.sh"
   volumes:
     - ./broker_helpers:/broker_helpers
